name: weather-checker
services:
  postgres:
    container_name: ${POSTGRES_HOST}
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    container_name: weather-server
    build:
      context: .
      target: production
    env_file:
      - .env
    ports:
      - 8800:8888
    depends_on:
      postgres:
        condition: service_healthy
